### PR TITLE
Feature/team 12 all directory

### PR DESCRIPTION
**Pull request by rrcooper467**
Shows the directory, workes with Windows. Includes commented basic locations for directory. There is a bug with drawing path from directory.
This branched from PhysicianDirectory which I am abandoning. :D

### CODE REVIEW

**Comment by rrcooper467** [comment]
Failing Travis CI checks is good, right?

**Comment by binamkayastha** [comment]
Looks like it's not working because of the getCurrentFloor() method which was removed in an earlier commit, and no longer exists on master.

Before doing a pull request, just be sure the program compiles/runs on your computer. (Right now it doesn't build). I'm not exactly sure what the best way of dealing with this is? 

Any ideas?

**Comment by rrcooper467** [comment]
It did run on my computer.....

**Comment by binamkayastha** [comment]
Okay I see, I was checking the wrong branch sorry. 

Travis CI is failing because of your HardcodeLocation.java file, where you're trying to create new nodes by doing addNode(10, 10), but addNode actually takes in a Location

**Pull request closed without merging**
